-- AlterTable
ALTER TABLE `building` ADD COLUMN `city` VARCHAR(191) NULL,
    ADD COLUMN `columns` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `country` VARCHAR(191) NULL,
    ADD COLUMN `rows` INTEGER NOT NULL DEFAULT 1;
